export interface AIService {
  draftInvoiceText(input: { projectSummary: string; workPerformed: string; notes?: string }): Promise<string>;
  draftFieldReviewNarrative(input: { rawNotes: string; projectContext: string }): Promise<string>;
}

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export const mockAIService: AIService = {
  async draftInvoiceText({ projectSummary, workPerformed, notes }) {
    await delay(200);
    return [
      `Project: ${projectSummary}`,
      `Summary of work: ${workPerformed}`,
      `Billing notes: ${notes ?? "Standard terms apply."}`,
      "This draft was generated by FirmLynk AI. Please review before sending.",
    ].join("\n\n");
  },
  async draftFieldReviewNarrative({ rawNotes, projectContext }) {
    await delay(200);
    return [
      `Context: ${projectContext}`,
      `Observations: ${rawNotes}`,
      "Recommendations: Coordinate with the contractor to address noted items prior to next milestone.",
      "Safety/Quality: No critical issues observed; continue monitoring high-risk areas.",
      "Generated by FirmLynk AI — edit as needed before finalizing.",
    ].join("\n\n");
  },
};

